version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    cooldown:
      default-days: 1
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: ci(deps)
    labels:
      - ci
      - dependencies
      - triage

  # Maintain dependencies for NPM
  - package-ecosystem: npm
    cooldown:
      default-days: 1
    directory: /
    schedule:
      interval: weekly
      day: monday
    versioning-strategy: increase
    commit-message:
      prefix: build(deps)
      prefix-development: build(dev-deps)
    labels:
      - npm
      - dependencies
      - triage
