env:
  browser: true
  es2021: true
  node: true
extends: noir/all
parserOptions:
  project: ./tsconfig.json
  ecmaVersion: latest
  sourceType: module
rules:
  import/extensions: off
  import/no-relative-parent-imports: off
  "@typescript-eslint/no-magic-numbers": off
