name: CI

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  knip:
    name: Knip

    runs-on: ubuntu-latest

    timeout-minutes: 30

    continue-on-error: true

    steps:
      - uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: .node-version

      - name: Set up PNPM
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check dead code/deps
        run: pnpm knip

  build:
    name: Build

    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: .node-version

      - name: Set up PNPM
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the project
        run: pnpm build

  typecheck:
    name: Type Check

    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: .node-version

      - name: Set up PNPM
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check the project
        run: pnpm typecheck

  lint:
    name: Lint

    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: .node-version

      - name: Set up PNPM
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check code styles
        run: pnpm lint

  document:
    name: Document

    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: .node-version

      - name: Set up PNPM
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate code documents
        run: pnpm document

  commitlint:
    name: Commit Lint

    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: .node-version

      - name: Set up PNPM
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check commit messages
        if: ${{ github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}
        run: pnpm commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  test:
    name: Test

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        node-version:
          - 24
          - 25
          - 26

    runs-on: ${{ matrix.os }}

    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v7

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up PNPM
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v3

      - name: Test the project
        run: pnpm test --ci --verbose --no-cache --maxWorkers ${{ steps.cpu-cores.outputs.count }}

  coverage:
    name: Report Code Coverage

    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: .node-version

      - name: Set up PNPM
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v3

      - name: Collect code coverage
        run: pnpm test:coverage --ci --no-cache --maxWorkers ${{ steps.cpu-cores.outputs.count }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: REF
          fail_ci_if_error: true
        env:
          REF: ${{ github.ref_name }}

  test-summary:
    name: Test Summary

    needs:
      - build
      - lint
      - document
      - commitlint
      - test
      - coverage

    if: ${{ always() && github.event_name == 'pull_request' }}

    runs-on: ubuntu-latest

    steps:
      - name: Check ci status
        if: ${{ needs.knip.result != 'success' || needs.build.result != 'success' || needs.typecheck.result != 'success' || needs.lint.result != 'success' || needs.document.result != 'success' || needs.commitlint.result != 'success' || needs.test.result != 'success' || needs.coverage.result != 'success' }}
        run: exit 1
