name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

env:
  NODE_VERSION: 20
  PNPM_VERSION: 9

jobs:
  test:
    uses: ./.github/workflows/test.yaml

  release:
    name: Create Release

    needs:
      - test

    environment:
      name: release
      url: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}

    concurrency:
      group: ${{ github.workflow }}-release-${{ github.ref_name }}
      cancel-in-progress: true

    runs-on: ubuntu-latest

    outputs:
      release-id: ${{ steps.changelog.outputs.release-id }}

    steps:
      - uses: actions/checkout@v4

      - name: Changelog
        id: changelog
        uses: ardalanamini/auto-changelog@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ${{ steps.changelog.outputs.changelog }}
          prerelease: ${{ steps.changelog.outputs.prerelease }}

  publish-documents:
    name: Publish Documents

    needs:
      - release

    permissions:
      actions: read
      contents: read
      pages: write
      id-token: write

    environment:
      name: documents
      url: ${{ steps.github-pages-deployment.outputs.page_url }}

    concurrency:
      group: ${{ github.workflow }}-documents-${{ github.ref_name }}
      cancel-in-progress: true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use PNPM ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: pnpm i

      - name: Generate code documents
        run: pnpm document

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/'

      - name: Deploy to GitHub Pages
        id: github-pages-deployment
        uses: actions/deploy-pages@v4

  publish-gpr:
    name: Publish to GitHub Packages

    needs:
      - release

    permissions:
      contents: read
      packages: write
      id-token: write

    environment:
      name: gpr
      url: https://github.com/${{ github.repository }}/pkgs/npm/utils

    concurrency:
      group: ${{ github.workflow }}-gpr-${{ github.ref_name }}
      cancel-in-progress: true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use PNPM ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com/
          scope: '@extremejs'

      - name: Install dependencies
        run: pnpm i

      - name: Publish the package
        run: pnpm publish --no-git-checks --tag ${{ needs.release.outputs.release-id }}
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}

  publish-npm:
    name: Publish to NPM

    needs:
      - release

    permissions:
      contents: read
      id-token: write

    environment:
      name: npm
      url: https://www.npmjs.com/package/@${{ github.repository }}

    concurrency:
      group: ${{ github.workflow }}-npm-${{ github.ref_name }}
      cancel-in-progress: true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use PNPM ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: pnpm i

      - name: Publish the package
        run: pnpm publish --no-git-checks --tag ${{ needs.release.outputs.release-id }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
