name: Test

on:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - main
  pull_request:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  test:
    name: Test

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node-version:
          - 16
          - 17
          - 18

    runs-on: ${{ matrix.os }}

    timeout-minutes: 15

    env:
      OS: ${{ runner.os }}
      ARCH: ${{ runner.arch }}
      NODE_VERSION: ${{ matrix.node-version }}
      REF: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up node modules cache
        id: node-modules-cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          restore-keys: |
            node-modules-cache-${{ runner.os }}-${{ runner.arch }}-${{ matrix.node-version }}-
            node-modules-cache-${{ runner.os }}-${{ runner.arch }}-
          key: node-modules-cache-${{ runner.os }}-${{ runner.arch }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        if: ${{ steps.node-modules-cache.outputs.cache-hit != 'true' }}
        run: npm i --no-fund

      - name: Check code styles
        run: npm run lint

      - name: Build for ECMAScript
        run: npm run build:esm

      - name: Build for CommonJS
        run: npm run build:cjs

      - name: Generate code documents
        run: npm run document

      - name: Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v1

      - name: Test the project
        run: npm run test:ci -- --maxWorkers ${{ steps.cpu-cores.outputs.count }}

      - name: Upload coverage to CodeCov
        uses: codecov/codecov-action@v3
        if: ${{ github.event_name != 'schedule' }}
        with:
          env_vars: OS,ARCH,NODE_VERSION,REF
          fail_ci_if_error: true
